# Generated by Django 3.2.8 on 2021-10-08 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_poetaccount_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poetaccount',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='poetaccount',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
