# Generated by Django 3.2.9 on 2022-01-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_poem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
