# Generated by Django 3.2.9 on 2022-02-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_auto_20220217_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ink',
            old_name='tweet',
            new_name='poem',
        ),
    ]
