# Generated by Django 3.2.9 on 2022-02-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0010_auto_20220217_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ink',
            old_name='timestamp',
            new_name='date_ink_given',
        ),
    ]
