# Generated by Django 3.2.9 on 2022-02-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_rename_timestamp_ink_date_ink_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ink',
            old_name='date_ink_given',
            new_name='date_given',
        ),
    ]
